### PR TITLE
Kyverno-JSON policies for Terraform and Dockerfiles

### PR DESCRIPTION
**Pull request by fykaa**

### CODE REVIEW

**Review by anusha94 — APPROVED** [review]

**Comment by anusha94** [comment]
Your folder structure now is
`terraform-best-practices/aws/ecs/terrafom` - seems repetitive. You can drop the last terraform folder.

**Review by anusha94 — CHANGES_REQUESTED** [review]
restructure directories.

**Comment by nitishfy** [comment]
Updated PR: https://github.com/nirmata/kyverno-policies/pull/129
cc: @anusha94

**Comment by fykaa** [comment]
@anusha94 For the failed test cases in PR #129, it's advisable to merge this PR initially. Then, once the merge branch is synchronized with the previous changes, proceed to merge PR #129. This ensures that main branch remains in its most up-to-date state.

**Comment by anusha94** [comment]
@fykaa @nitishfy Let's merge only Dockerfile policies for now. Can either of you update the PR please?

**Comment by anusha94** [comment]
Dockerfile policies are already added. Terraform policies we will add at a later point. Closing this PR for now.

**Pull request closed without merging**
